# Generated by Django 4.0.4 on 2022-12-31 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=4)),
                ('rated', models.CharField(max_length=10)),
                ('released', models.CharField(max_length=20)),
                ('runtime', models.CharField(max_length=10)),
                ('genre', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=200)),
                ('actors', models.CharField(max_length=200)),
                ('plot', models.CharField(max_length=1000)),
                ('language', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('awards', models.CharField(max_length=200)),
                ('poster_url', models.URLField()),
                ('ratings', models.TextField()),
                ('imdb_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('imdb_votes', models.CharField(max_length=10)),
                ('imdb_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('box_office', models.CharField(max_length=20)),
                ('production', models.CharField(max_length=200)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=4)),
                ('rated', models.CharField(max_length=10)),
                ('released', models.CharField(max_length=20)),
                ('runtime', models.CharField(max_length=10)),
                ('genre', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=200)),
                ('actors', models.CharField(max_length=200)),
                ('plot', models.CharField(max_length=1000)),
                ('language', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('awards', models.CharField(max_length=200)),
                ('poster_url', models.URLField()),
                ('ratings', models.TextField()),
                ('imdb_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('imdb_votes', models.CharField(max_length=10)),
                ('imdb_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('total_seasons', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('movies', models.ManyToManyField(to='main.movie')),
                ('shows', models.ManyToManyField(to='main.show')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
