# Generated by Django 4.0.4 on 2022-12-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_movie_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='ratings',
            field=models.JSONField(null=True),
        ),
    ]
